react-hook-form/resolvers

- tsconfig.json
> exclude test file from tsc build target

- README.md
Hey Maintainers, 
I am just starting out here but this is not  big change,
I just realized that the grammar in the documentation page could be improved for better understanding.
> Grammar in the Goal section of the README.md file corrected

- tsconfig.json
> change target ES2017 to es5

- package.json
- src/joi.ts
- src/superstruct.ts
- src/yup.ts
- yarn.lock
related https://github.com/react-hook-form/react-hook-form/pull/2733
> import types from core lib

- src/__snapshots__/yup.test.ts.snap
- src/yup.test.ts
- src/yup.ts
fix #53 
https://codesandbox.io/s/react-hook-form-mui-yup-forked-s6mb8?file=/demo.tsx
> fix errors with validateAllFieldCriteria

- src/index.ie11.ts
related https://github.com/react-hook-form/react-hook-form/pull/2870
> add declaration types for ie11

- README.md
- package.json
- src/joi.test.ts
- src/joi.ts
- yarn.lock
Related to https://github.com/react-hook-form/resolvers/issues/79
> Replace deprecated @hapi/joi by joi

- .changeset/config.json
- .github/workflows/release.yml
- package.json
- yarn.lock
- Update changesets version
- Update release github action (use yarn for consistency): https://github.com/changesets/action
- Add release script
This [error](https://github.com/react-hook-form/resolvers/runs/1623847184) should be fixed
> Re-setup changesets

- .changeset/orange-starfishes-agree.md
Let's try a release ! 🚀 
According to the [doc](https://github.com/atlassian/changesets/blob/master/packages/cli/README.md#base-workflow)
As contributor:
> Release 1.3.1

- yup/src/__tests__/__snapshots__/yup.ts.snap
- yup/src/__tests__/yup.ts
- yup/src/types.ts
- yup/src/yup.ts
- zod/src/__tests__/__snapshots__/zod.ts.snap
- zod/src/__tests__/zod.ts
Related to #88 
- Add Yup sync validation
- Add Zod tests (async/sync mode)
> Yup sync validation

- src/joi.test.ts
- src/joi.ts
> fix: Joi pass context from useForm

- joi/src/__tests__/__fixtures__/data.ts
- joi/src/__tests__/__snapshots__/joi.ts.snap
- joi/src/__tests__/joi.ts
- joi/src/joi.ts
- src/__tests__/toNestObject.ts
- src/index.ts
- src/toNestError.ts
- src/toNestObject.ts
- superstruct/src/__tests__/__fixtures__/data.ts
- superstruct/src/__tests__/__snapshots__/superstruct.ts.snap
- superstruct/src/__tests__/superstruct.ts
- superstruct/src/superstruct.ts
- vest/src/__tests__/__fixtures__/data.ts
- vest/src/__tests__/__snapshots__/vest.ts.snap
- vest/src/__tests__/vest.ts
- vest/src/vest.ts
- yup/src/__tests__/__fixtures__/data.ts
- yup/src/__tests__/__snapshots__/yup.ts.snap
- yup/src/__tests__/yup.ts
- yup/src/yup.ts
- zod/src/__tests__/__fixtures__/data.ts
- zod/src/__tests__/__snapshots__/zod.ts.snap
- zod/src/__tests__/zod.ts
- zod/src/zod.ts
- Add error's ref 🆕 
- Rename `toNestObject` to `toNestError`
- Add nested test case for each resolvers
- Extract tests's fixtures in separate file to improve readability
> Add error's ref

- src/yup.ts
related to #92 & #31
feedback is welcome 😃
passed all local test
> fix: add Lazy schema support to yup resolver

- .github/workflows/main.yml
- package.json
I created the 1.x maintenance branch.
This PR adds the semantic-release config
> chore: setup semantic-release for 1.x maintenance

- .github/workflows/main.yml
- package.json
- yarn.lock
> V1 - release process cleanup

- .github/workflows/main.yml
- package.json
- yarn.lock
All the release process is handled in the main.yml
> Release process cleanup

- .vscode/settings.json
- README.md
- class-validator/package.json
- class-validator/src/__tests__/Form.tsx
- class-validator/src/__tests__/__fixtures__/data.ts
- class-validator/src/__tests__/__snapshots__/class-validator.ts.snap
- class-validator/src/__tests__/class-validator.ts
- class-validator/src/class-validator.ts
- class-validator/src/index.ts
- class-validator/src/types.ts
- config/node-13-exports.js
- package.json
- tsconfig.json
- yarn.lock
This PR adds `class-validator` resolver with basic tests. In addition it fixes the prettier configPath and the copy function.
> Add class validator resolver

- README.md
Noticed the schema for the example didn't make sense, minor updates for the example code
> Minor Readme updates for joi example

- README.md
- config/node-13-exports.js
- package.json
- typanion/package.json
- typanion/src/__tests__/Form-native-validation.tsx
- typanion/src/__tests__/Form.tsx
- typanion/src/__tests__/__fixtures__/data.ts
- typanion/src/__tests__/__snapshots__/typanion.ts.snap
- typanion/src/__tests__/typanion.ts
- typanion/src/index.ts
- typanion/src/typanion.ts
- typanion/src/types.ts
- yarn.lock
I believe I covered everything except adding it to the Bug Report template which seems to be lacking a few other resolvers currently as well.
Fixes https://github.com/react-hook-form/react-hook-form/discussions/6099
> Add Typanion Resolver

- README.md
- ajv/package.json
- ajv/src/__tests__/Form-native-validation.tsx
- ajv/src/__tests__/Form.tsx
- ajv/src/__tests__/__fixtures__/data.ts
- ajv/src/__tests__/__snapshots__/ajv.ts.snap
- ajv/src/__tests__/ajv.ts
- ajv/src/ajv.ts
- ajv/src/index.ts
- ajv/src/types.ts
- config/node-13-exports.js
- package.json
- yarn.lock
~~There are **2 problems** need to be solved~~
1. ~~`mjs` file cannot be created when build. But I have add the build script.~~
2. ~~If field is **required**, user must add `minLength: 1` in the schema. Does this need to be optimized?~~
close #309
> feat: add ajv

- package.json
- pnpm-lock.yaml
> chore: add `cross-env` for windows compatibility

- package.json
- pnpm-lock.yaml
- yup/src/__tests__/__fixtures__/data.ts
- yup/src/__tests__/__snapshots__/yup.ts.snap
- yup/src/__tests__/yup.ts
- yup/src/types.ts
This might be a breaking change. @bluebill1049 Can you juste review (and approve) but do not merge please 🙏🏻 
Fix: #508
> feat(yupResolver): add support Yup v1

- class-validator/src/__tests__/__snapshots__/class-validator.ts.snap
- class-validator/src/__tests__/class-validator.ts
- class-validator/src/class-validator.ts
- class-validator/src/types.ts
@bluebill1049 you can review but do not merge. There is a breaking change
Fix #445
> feat(classValidationResolver): add transform and validator options

- README.md
- config/node-13-exports.js
- package.json
- pnpm-lock.yaml
- typebox/package.json
- typebox/src/__tests__/Form-native-validation.tsx
- typebox/src/__tests__/Form.tsx
- typebox/src/__tests__/__fixtures__/data.ts
- typebox/src/__tests__/__snapshots__/typebox.ts.snap
- typebox/src/__tests__/typebox.ts
- typebox/src/index.ts
- typebox/src/typebox.ts
- typebox/src/types.ts
> feat(typeboxResolver): add TypeBox resolver

- package.json
- pnpm-lock.yaml
Due to https://github.com/advisories/GHSA-m95q-7qp3-xv42
> Upgrading `zod` dependency

- package.json
- pnpm-lock.yaml
- src/toNestErrors.ts
> fix: migrate set to lodash.set package

- README.md
- config/node-13-exports.js
- package.json
- pnpm-lock.yaml
- vine/package.json
- vine/src/__tests__/Form-native-validation.tsx
- vine/src/__tests__/Form.tsx
- vine/src/__tests__/__fixtures__/data.ts
- vine/src/__tests__/__snapshots__/vine.ts.snap
- vine/src/__tests__/vine.ts
- vine/src/index.ts
- vine/src/types.ts
- vine/src/vine.ts
Adds a resolver for [VineJS](https://vinejs.dev/) library.
> feat: add VineJS resolver

- README.md
Signed-off-by: Jonathan Powers <jonathan.powers@storable.com>
> feat: update to effect 3.10

- arktype/src/types.ts
Fixes #730 
@bluebill1049 Review is welcome, but please don’t merge. Thank you!
> fix(arktypeResolver): resolve type error when schema is defined from an ArkType scope

- .github/workflows/compressedSize.yml
- bun.lock
- package.json
> fix(standard-schema): move @standard-schema/utils to dependencies
