react-hook-form/resolvers

package.json

Prepend `dist/` directory to jsnext:main entry point

Fix jsnext:main entry point

---

src/yup.test.ts
src/yup.ts

Hey there,
-> https://github.com/react-hook-form/resolvers/issues/29
Test + context injected
I prefer to don't dive test because i will make another mr for -> https://github.com/react-hook-form/resolvers/issues/26#issuecomment-659114319.
And then push test to 100%

feat(context): inject context into yup context

---

src/yup.ts

Hi! I want to use Yup.lazy, but I get a type error.
https://codesandbox.io/s/lingering-frog-0bryw?file=/src/App.tsx
It worked fine when I changed the type to any, so I added the `Lazy` type to Schema.
Lazy seems to be the same as the Schema type.
```
// tslint:disable-next-line:no-empty-interface
export interface Lazy extends Schema<any> {}
```

add Lazy Type

---

src/__snapshots__/yup.test.ts.snap
src/yup.test.ts
src/yup.ts

**At the same time:** 
**Improvements which can be done into**
1.  For an array, If we remove the `transformToNestObject` we will have at the same time array errors and all field errors inside this array.
Cons: errors duplication : 
```
foo[0].test: {
message: ...,
type: ...,
types: [ ] | {}
},
foo: [
{ 
test: {
message: ...,
type: ...,
types: [ ] | {}
}
},
...
]
```
Pros: it can be interesting to have it to get at the same time array errors and fields errors in.
We could maybe do : `validateAllFieldCriteria ? call transformToNestObject `
You can have example of use case here -> https://github.com/react-hook-form/resolvers/issues/26#issuecomment-660498288
From issue -> https://github.com/react-hook-form/resolvers/issues/26
2. On first try to rhf we don't know where to place the context …

Support multiple errors messages

---

rollup.config.js
rollup/createRollupConfig.js
tsconfig.ie11.json

Usage:
```ts
import { yupResolver } from '@hookform/resolvers/dist/index.ie11.js';
```
if using TS:
create declaration file (`.d.ts`).
```ts
// global.d.ts
declare module '@hookform/resolvers/dist/index.ie11.js' {
export * from '@hookform/resolvers';
}
```
if using webpack:
Note: not neeed to create declaration file if using TS.
```ts
import { yupResolver } from '@hookform/resolvers';
```
```js
// webpack.config.js
resolve: {
alias: {
"@hookform/resolvers": "@hookform/resolvers/dist/index.ie11.js"
}
}
```
close #42
related https://github.com/react-hook-form/resolvers/pull/40

improve rollup config to support IE11

---

package.json
rollup.config.js
rollup/cjs.ie11.js
rollup/merge-config.js
rollup/umd.js
yarn.lock

👋🏻 
Related to https://github.com/react-hook-form/resolvers/issues/64
Use rollup instead of tsc to bundle ie11.
`paths` allow to rewrite import in order to use the right version of react-hook-form and then fix the issue.
```js
paths: {
'react-hook-form': 'react-hook-form/dist/index.ie11',
},
```

Use right version of react-hook-form for ie11 bundle

---

rollup/cjs.ie11.js

👋🏻 
Related to https://github.com/react-hook-form/resolvers/issues/64#issuecomment-717076880, workaround: https://github.com/react-hook-form/resolvers/issues/64#issuecomment-716614092
Allow to generate TS declaration files for ie11 build which produce the following result and no more workaround needed :)

Add TS declaration files to ie11 build

---

rollup/cjs.ie11.js
rollup/merge-config.js
rollup/umd.js

Related to https://github.com/react-hook-form/resolvers/issues/84.

Fix IE11 bundle

---

README.md
jest.config.js

For some reason the Zod example implemented a different form from the other 3 examples, so I decided to standardize it wiht the others. In the process of doing that I realized the sample was buggy because the Zod schema didn't convert the `age` string into a number. This makes sense because Zod v1 (which the author of the resolver was using) didn't support value transformations. I was planning to upgrade the example to use Zod 2 (which is capable of converting the string to a number) but then I saw that support for `valueAsNumber` was just introduced! Which is SUCH a gamechanger, thanks Bill! Because of that I was able to fix this example without dropping support for Zod v1.

Fixing and standardizing Zod example

---

src/yup.test.ts
src/yup.ts

Related to https://github.com/react-hook-form/resolvers/issues/97
I just put the original types back for the yup resolver.
I plan to improve them in V2 for all resolvers

fix: yup resolver TypeScript errors

---

zod/src/__tests__/__snapshots__/zod.ts.snap
zod/src/__tests__/zod.ts
zod/src/types.ts
zod/src/zod.ts

Related to https://github.com/react-hook-form/resolvers/issues/88
Starting with Zod, same for others resolvers coming :)

Zod sync validation

---

joi/src/__tests__/__snapshots__/joi.ts.snap
joi/src/__tests__/joi.ts
joi/src/joi.ts
joi/src/types.ts

Joi sync validation

---

joi/src/__tests__/Form.tsx
joi/src/__tests__/joi.ts
joi/src/joi.ts
joi/src/types.ts
package.json
superstruct/src/__tests__/Form.tsx
superstruct/src/__tests__/superstruct.ts
superstruct/src/superstruct.ts
superstruct/src/types.ts
vest/src/__tests__/Form.tsx
vest/src/__tests__/vest.ts
vest/src/types.ts
vest/src/vest.ts
yarn.lock
yup/src/__tests__/Form.tsx
yup/src/__tests__/yup.ts
yup/src/types.ts
yup/src/yup.ts
zod/package.json
zod/src/__tests__/Form.tsx
zod/src/__tests__/zod.ts
zod/src/types.ts
zod/src/zod.ts

Next step: remove `transformToNestObject`

Update to react-hook-form v7

---

src/__snapshots__/zod.test.ts.snap
src/zod.test.ts
src/zod.ts

I noticed that the errors for array elements are not exposed in the Zod resolver. In the current version, the error looks like this instead (notice it doesn't expose the index of the validation error):
```
"likedUsers": Object {
"message": "Invalid input",
"type": "invalid_union",
"types": Object {
"invalid_union": "Invalid input",
},
},
```
- I updated the resolver to look at `unionErrors` when parsing errors from Zod to fix this error. Only `ZodInvalidUnionError` can have other errors as field values. So checking the existence of `unionErrors` should be good enough. But I am open to ideas here.
- I changed the original code's `reduce` to a queue to handle deeply nested union errors.

fix: expose array element validation errors in zod resolver

---

joi/src/__tests__/joi.ts
joi/src/joi.ts

fix: pass down Joi context

---

jest.config.js
zod/src/__tests__/__fixtures__/data.ts
zod/src/__tests__/__snapshots__/zod.ts.snap
zod/src/__tests__/zod.ts
zod/src/types.ts
zod/src/zod.ts

- Fix Zod resolver union error (same as https://github.com/react-hook-form/resolvers/pull/119)
- Extract test fixtures
- Reduce zod resolver size

Zod fix union error + reduce resolver size

---

README.md
class-validator/package.json
class-validator/src/__tests__/__snapshots__/class-validator.ts.snap
class-validator/src/__tests__/class-validator.ts
class-validator/src/class-validator.ts

- [Fix nested errors](https://github.com/react-hook-form/resolvers/commit/bcdf56bfea15a93301876c6af3a816d08d321298)
- [support `criteriaMode: all`](https://github.com/react-hook-form/resolvers/commit/a419de2aac2ceca9a92a4db5b47c0553ccac3464)
- [perf: reduce bundle size (~93% per bundle)](https://github.com/react-hook-form/resolvers/commit/c61fd8f845c2ba0024c2819ce9ecde11e668dbc6)
- Fix warning at build time: 
>The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

add `criteriaMode: all` support to class-validator resolver

---

README.md

`import reflect-metadata` is not needed in this example. I left it by mistake.
It is needed when you use `class-transformer`, e.g.
```tsx
import "reflect-metadata"; // Here! But it's preffered to import it only once in place like `src/index.tsx`
import { Length, ValidateNested } from "class-validator";
import { Type } from "class-transformer"; // So we must import reflect-metadata, like above ^
class Friend {
@Length(3, 30)
username: string;
}
export class User {
@Length(3, 30)
username: string;
@ValidateNested()
@Type(() => Friend)
bestFriend: Friend;
}
```

Remove redundant reflect metadata import

---

yup/src/__tests__/__fixtures__/data.ts
yup/src/__tests__/__snapshots__/yup.ts.snap
yup/src/yup.ts

Related to #155 
I'll update the v1 as well

fix(yupResolver): multiple errors messages with same type

---

class-validator/src/__tests__/Form-native-validation.tsx
class-validator/src/class-validator.ts
computed-types/src/__tests__/Form-native-validation.tsx
computed-types/src/computed-types.ts
io-ts/src/__tests__/Form-native-validation.tsx
io-ts/src/io-ts.ts
joi/src/__tests__/Form-native-validation.tsx
joi/src/joi.ts
nope/src/__tests__/Form-native-validation.tsx
nope/src/nope.ts
src/__tests__/__snapshots__/toNestObject.ts.snap
src/__tests__/toNestObject.ts
src/__tests__/validateFieldsNatively.ts
src/index.ts
src/toNestError.ts
src/validateFieldsNatively.ts
superstruct/src/__tests__/Form-native-validation.tsx
superstruct/src/superstruct.ts
vest/src/__tests__/Form-native-validation.tsx
vest/src/vest.ts
yup/src/__tests__/Form-native-validation.tsx
yup/src/yup.ts
zod/src/__tests__/Form-native-validation.tsx
zod/src/zod.ts

Related to https://github.com/react-hook-form/resolvers/issues/182

fix(native-validation): clear error

---

.github/dependabot.yml
yarn.lock

Update of the update's frequency. Currently, Dependabot does not support Pr grouping.
@bluebill1049 Do you want something similar on the main repo?

ci: run dependabot weekly on sunday

---

class-validator/src/__tests__/Form-native-validation.tsx
class-validator/src/__tests__/Form.tsx
class-validator/src/types.ts
io-ts/src/__tests__/Form-native-validation.tsx
io-ts/src/__tests__/Form.tsx
io-ts/src/io-ts.ts
io-ts/src/types.ts
joi/src/types.ts
nope/src/types.ts
package.json
src/toNestError.ts
superstruct/src/__tests__/Form.tsx
superstruct/src/superstruct.ts
superstruct/src/types.ts
typanion/src/__tests__/Form-native-validation.tsx
typanion/src/__tests__/Form.tsx
typanion/src/typanion.ts
typanion/src/types.ts
vest/src/types.ts
yarn.lock
yup/src/__tests__/Form-native-validation.tsx
yup/src/__tests__/Form.tsx
yup/src/types.ts
yup/src/yup.ts
zod/src/__tests__/Form.tsx
zod/src/types.ts
zod/src/zod.ts

I upgraded to the latest `react-hook-form` and `@hookform/resolvers` versions and all of a sudden all my forms that were using the `yupResolver` were throwing a typescript error while those using the io-ts resolver (I'm progressively migrating to io-ts) didn't.
I checked what could be the source and figured the typings were not infered properly when wrapping the generic function.
Example of something that does not work:
```typescript
const { register } = useForm<Type>({
resolver: yupResolver(schema),
});
```
Fixes #234

Fix resolvers typings with `react-hook-form@7.15.0`

---

README.md

`.nonempty()` is deprecated adn replaced by `.min(1)` as per zod documentation.
See https://github.com/colinhacks/zod#strings

zod.nonempty() is deprecated

---

zod/src/__tests__/__fixtures__/data.ts
zod/src/__tests__/__snapshots__/zod.ts.snap
zod/src/__tests__/zod.ts
zod/src/types.ts
zod/src/zod.ts

When using [tRPC](https://trpc.io/), it's common to use the same validation schema on the server as the client. Therefore, it's good to be able to send the unparsed raw values from the client to the server.
Maybe this should be the default behavior, unsure if it's intentional to be as it is.

Add ability to skip zod's parsing

---

README.md
class-validator/src/types.ts
nope/src/types.ts
typanion/src/types.ts
vest/src/types.ts
yup/src/types.ts
yup/src/yup.ts

update types for all resolvers
```tsx
type Options = { 
mode: 'async' | 'sync',
rawValues?: boolean 
}
resolver(schema: object, schemaOptions?: object, resolverOptions: Options)
````

feat: update for resolvers with new `rawValues` option

---

ajv/src/__tests__/__fixtures__/data.ts
ajv/src/__tests__/__snapshots__/ajv.ts.snap
ajv/src/ajv.ts

The current implementation of `ajv` resolver didn't support well more than 2 layers of nesting. The error keys wouldn't match the shape of the data. See below `data/category`.
The below schema results in:
```js
{
type: 'object', 
properties: {
row: {
type: 'object',
properties: {
name: {
type: 'string',
minLength: 10,
errorMessage: { minLength: 'Username should be at least 10 characters' },
},
data: {
type: 'object',
properties: {
category: {
type: 'string',
minLength: 1,
errorMessage: { minLength: 'Category is required' },
}
},
required: ['category'],
additionalProperties: true,
}
},
required: ['name', 'data'],
additionalProperties: true,
},
},
required: ['row'],
additionalProperties: false,
};
```
The fix is to essentially replace all occurrences of `/` instead of only the first one.

fix: ajv resolver to work with unlimited layers of nesting

---

io-ts/src/io-ts.ts

Unlike other import statements, this one points not to `fp-ts/Either` but to `fp-ts/lib/Either`, which is a CommonJS file (`node_modules/fp-ts/lib/Either.js`).
This causes an error when you import `@hookform/resolvers/io-ts` from a ES module, where a file extension is mandatory in import sources, as `fp-ts/lib/Either` lacks `.js` extension.
Importing from `fp-ts/Either` (just as all other imports do so) solves the problem, since the `package.json` switches CJS/ESM.

Prefer `fp-ts/Either` over `fp-ts/lib/Either`

---

computed-types/src/__tests__/Form.tsx
computed-types/src/__tests__/__fixtures__/data.ts
computed-types/src/__tests__/__snapshots__/computed-types.ts.snap
computed-types/src/computed-types.ts

Having nested fields (represented by a nested `Schema` in computed-types) did not produce the expected error messages.
This change fixes it by using paths with dot syntax as the errors key, which will be correctly converted by `toNestError`.

Fix nested schema with computed-types

---

ajv/package.json
class-validator/package.json
computed-types/package.json
io-ts/package.json
joi/package.json
nope/package.json
superstruct/package.json
typanion/package.json
vest/package.json
yup/package.json
zod/package.json

This PR addresses the issue raised here: https://github.com/react-hook-form/resolvers/issues/423
This change was pretty minor but I did have a couple of questions:
- Would you prefer if I changed the path for these dependencies as well? I decided against it because it might be a breaking change but I can update the PR with that if you'd like.
- I get a warning about the new package names due to the double forward slashes (/) failing the regex. It doesn't have an impact since these are private packages but I wasn't sure if you would rather I use a different naming convention. Something like "@hookform/resolvers.ajv" perhaps.

Renamed private packages to avoid ambiguity with existing official packages. This should mitigate false positives during image scans.

---

yup/src/yup.ts

Hi,
Yup was imported with a default import [but in the original library no default export is defined](https://github.com/jquense/yup/blob/master/src/index.ts). This is only working at the moment when building the lib because of the tsconfig option `esModuleInterop`.
I believe this is causing an issue only in specific scenarios (I had the issue while using a Webpack 4 setup with an older ts-loader version) but since it's a tiny change, might be reasonable to fix.
This is the error you could eventually see and this PR resolve:
`TS1192: Module '"/node_modules/@hookform/resolvers/yup/src/yup"' has no default export.`

fix(yup): fix Yup wrong import statement assuming default export

---

package.json

Fixes #396
This library is exporting multiple builds (umd/module/cjs) but duplicates the CJS ("require") build as the "browser" build. This is not required for this project; "browser" is supposed to be used for distinguishing browser-specific versions (e.g. if using Node `crypto` package when built for NodeJS vs. using browser-standard cryptography when built for browsers), whereas this project does not use any node-specific or browser-specific builds.
Jest's latest update reworks their import handling to properly support package.json `exports`, which has revealed this issue (Jest is now — correctly — using the `browser` import, but failing because it cannot handle esm modules)
By removing the browser entries entirely, all build systems will pick the appropriate build based on whether …

Remove unnecessary 'browser' exports to fix Jest integration

---

io-ts/src/types.ts

The `Resolver` type was missing a constraint on one of the generics, leading to the following error if not using `skipLibCheck`:
```
node_modules/@hookform/resolvers/io-ts/dist/types.d.ts:3:177 - error TS2344: Type 'TFieldValues' does not satisfy the constraint 'FieldValues'.
3 export declare type Resolver = <T, TFieldValues, TContext>(codec: t.Decoder<FieldValues, T>) => (values: TFieldValues, _context: TContext | undefined, options: ResolverOptions<TFieldValues>) => ResolverResult<TFieldValues>;
~~~~~~~~~~~~
node_modules/@hookform/resolvers/io-ts/dist/types.d.ts:3:36
3 export declare type Resolver = <T, TFieldValues, TContext>(codec: t.Decoder<FieldValues, T>) => (values: TFieldValues, _context: TContext | undefined, options: ResolverOptions<TFieldValues>) => …
```

Fix types for io-ts resolver

---

README.md

GitHub site adds a copy to clipboard button to code samples. Having the `$` makes it invalid to paste. Remove it.

remove $ from script that is copyable

---

io-ts/src/__tests__/errorsToRecord.ts
io-ts/src/errorsToRecord.ts
yarn.lock

`exact(intersection(...))` structure would result in an undesirable result of a shape`{0: errorsRecord, 1: errorsRecord, ...}` whereas just exact(...) or just intersection(...) would correctly report errors of shape `errorsRecord`. 
This PR adds a test against it and resolves the bug.
UPD: same for Branded types
Bonus: caniuse-lite bumped a bit in package-lock

Fix ts-io resolver error reporting for exact(intersection(...))

---

vest/src/index.ts

Types export is missing for `vest` resolver.

fix(vest): add types export

---

vest/src/__tests__/vest.ts
vest/src/types.ts
vest/src/vest.ts

React Hook Form has a way to signal to a resolver for which fields validations were requested (`options.names`/`options.fields`) and Vest has a way to skip unrequested validations (`only`/`skip`/`include`). But currently that names information gets discarded and Vest cannot utilize that functionality. I think it makes sense to pass names as a second argument.
Note: `vestResolver` has a second argument which is and never was utilized, other adapters do not have such thing. I think it should be put on note somewhere for removal in next major release.

feat: pass `options.names` as a second argument to a Vest suite

---

yup/src/__tests__/yup.ts
yup/src/yup.ts

Approximate support for Yup's lazy schemas. Yup does not expose the lazy type.
Related to #567

fix(yup): lazy schema

---

yup/src/yup.ts

This PR addresses the issue outlined in https://github.com/react-hook-form/resolvers/issues/575. The problem stems from inaccurate inference of generics (`TFieldValue`) in `yupResolver`.
For instance, when passing a schema with optional keys to `yupResolver`:
```tsx
const schema = yup.object({ test: yup.number() });
type TestValues = yup.InferType<typeof schema>;
function Form({ values }: { values: TestValues }) {
const methods = useForm({
values: values,
resolver: yupResolver(testSchema)
});
return null;
}
```
The inferred type for `yupResolver` looks like this:
```ts
(alias) yupResolver<{
test: number | undefined;
}>(schema: Lazy<any, yup.Maybe<yup.AnyObject>, any> | yup.ObjectSchema<{
test: number | undefined;
}, yup.AnyObject, any, "">, schemaOptions?: yup.ValidateOptions<...> | ... 1 …
```

fix(yup): resolve ts error when including optional key in yup schema

---

typanion/src/typanion.ts

I noticed the split logic isn't correct, since it'll cut error messages if they happen to contain extra `:` characters.

Fixes typanion error messages when they contain `:`

---

.codesandbox/ci.json
package.json

This PR aims to resolve build errors on CodeSandbox CI as follows. The cause of these errors is related to running multiple builds in parallel.
https://ci.codesandbox.io/status/react-hook-form/resolvers/pr/638/builds/428549
- Updated Node.js to version 18, as the previous version was significantly outdated.
- To address build errors on CodeSandbox CI, we made modifications to execute multiple builds sequentially on CodeSandbox CI.

ci(codesandbox): fix CodeSandbox CI setting

---

package.json
pnpm-lock.yaml
valibot/src/__tests__/Form-native-validation.tsx
valibot/src/__tests__/__fixtures__/data.ts
valibot/src/__tests__/valibot.ts
valibot/src/valibot.ts

**Describe the bug**
In recent versions of valibot they've introduced a `variant` method. This method does not set a `path` value in the issues array. Because of the way the `valibotResolver` loops over the issues returned from valibot, this can cause an infinite loop.
**To Reproduce**
1. Using the following schema:
```ts
const numberSchema = object({
type: literal("number")
})
const stringSchema = object({
type: literal("string")
})
const typeSchema = variant("type", [numberSchema, stringSchema])
```
2. Try to call the valibot resolver.
```ts
const data = {
type: undefined
}
await valibotResolver(typeSchema, undefined, {
mode: 'sync',
})(data, undefined, {
fields,
shouldUseNativeValidation,
});
```
3. Browser or test runner freezes.
**Additional context**
I've included tests in this PR. …

Valibot infinate loop in resolver

---

src/__tests__/toNestErrors.ts
src/toNestErrors.ts

Fixes https://github.com/react-hook-form/resolvers/issues/629
Issue:
If you had a field array with two elements and an error in the second element THEN a root error, `.compact` would recognize the second element error as an error in the first element.
Solution:
Get rid of `.compact`

Fixes error handling for array errors with root error

---

arktype/package.json
arktype/src/__tests__/Form-native-validation.tsx
arktype/src/__tests__/Form.tsx
arktype/src/__tests__/__fixtures__/data.ts
arktype/src/__tests__/__snapshots__/arktype.ts.snap
arktype/src/arktype.ts
arktype/src/types.ts
package.json
pnpm-lock.yaml

The `latest` version of `arktype` is now `2.0.0-dev.14`, which is consistent with an upcoming major release.
I've created a new major version of the `@hookform/resolvers/arktype` to match this.
I did have a question as to whether it was okay to resuse the existing `errors.byPath` property with a `type` alias for `code` as `FieldErrors`. It would have many additional properties users could introspect, so long as nowhere in hookform is there an assumption that there are no extra properties on that object (as can be seen by the snapshots with many additional properties).
If extra properties are problematic, I can adjust the code to just include `message` and `type` as they did before.

migrate arktype resolver to v2

---

README.md
package.json
pnpm-lock.yaml
valibot/package.json
valibot/src/__tests__/Form-native-validation.tsx
valibot/src/__tests__/Form.tsx
valibot/src/__tests__/__fixtures__/data.ts
valibot/src/__tests__/__snapshots__/valibot.ts.snap
valibot/src/__tests__/valibot.ts
valibot/src/types.ts
valibot/src/valibot.ts

https://valibot.dev/guides/migrate-to-v0.31.0/

Upgrade and migrate Valibot to v0.31.0

---

package.json
pnpm-lock.yaml
valibot/package.json

Unfortunately, I introduced a breaking change in a type of Valibot v0.33.0. So I updated the dependencies.

chore: update valibot dependency to version >=0.33.0

---

zod/src/zod.ts

`ZodError` type expects `errors` prop to be an array
```ts
export declare class ZodError<T = any> extends Error {
issues: ZodIssue[];
get errors(): ZodIssue[];
constructor(issues: ZodIssue[]);
format(): ZodFormattedError<T>;
format<U>(mapper: (issue: ZodIssue) => U): ZodFormattedError<T, U>;
static create: (issues: ZodIssue[]) => ZodError<any>;
toString(): string;
get message(): string;
get isEmpty(): boolean;
addIssue: (sub: ZodIssue) => void;
addIssues: (subs?: ZodIssue[]) => void;
flatten(): typeToFlattenedError<T>;
flatten<U>(mapper?: (issue: ZodIssue) => U): typeToFlattenedError<T, U>;
get formErrors(): typeToFlattenedError<T, string>;
}
```
And `parseErrorSchema` function expects an array:
https://github.com/react-hook-form/resolvers/blob/f7a4fd46af51a2a732c10ed652f5abfa532f4198/zod/ …

isZodError: check if error.errors is actually an array

---

README.md
typebox/src/__tests__/Form-compiler.tsx
typebox/src/__tests__/Form-native-validation-compiler.tsx
typebox/src/__tests__/__snapshots__/typebox-compiler.ts.snap
typebox/src/__tests__/typebox-compiler.ts
typebox/src/typebox.ts
typebox/src/types.ts

- Current implementation only makes use of the dynamic validation (aka `ValueCheck`) of `TypeBox` but not its `TypeCompiler` (a high-performance JIT) which is a killer feature, especially when working with recursive or constrained type validation.
- Add options for the user to pass a `TypeCheck` object (returned from `TypeCompiler.Compile()`) instead of plain schema.
- Add tests
- Add document for using `TypeCompiler`
- Fix typo in tests of the `ValueCheck` mode (it mentioned `zod` instead of `typebox`)

feat(typeboxResolver): make TypeBox resolver work with compiled schema

---

valibot/package.json

Looks like the npm install broke with the upgrade to Valibot v1. This PR should fix that.

fix: Valibot peer dependency to support dist-tags

---

arktype/package.json

Version 2.0 was released: https://x.com/arktypeio/status/1880328086023217644

Use stable version for ArkType 2

---

src/__tests__/toNestErrors.ts
src/toNestErrors.ts

- https://github.com/react-hook-form/resolvers/issues/627
Because of https://github.com/react-hook-form/resolvers/pull/621, nested object error becomes not consistent when a key of the object is used in `option.names`.
**To Reproduce**
1. go to [codesandbox](https://codesandbox.io/p/sandbox/x65hh6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0b3xoks00063b6mue46slnk%2 …

fix: isNameInFieldArray with names option

---

ajv/src/__tests__/__fixtures__/data-errors.ts
ajv/src/__tests__/__snapshots__/ajv-errors.ts.snap
ajv/src/__tests__/__snapshots__/ajv.ts.snap
ajv/src/__tests__/ajv-errors.ts
ajv/src/ajv.ts
ajv/src/types.ts

When `errorMessage` is used, ajv returns a special error object, `error.keyword='errorMessage'`, and keeps original validation errors in the `error.errors` field.
The proposed changes normalize the ajv validation errors by unwrapping the `errorMessage` error object, so the resolver returns original error types, such as required and pattern, while using custom error messages. The normalization also allows us to use `errorMessage`  at the root level (fixes #615).
As you can see in the before and after outputs, the value of the `type` field and the keys of the `types` field use the original validation type instead of `errorMessage`.
**Before**
```json
"password": {
"message": "One uppercase character",
"ref": {
"name": "password",
},
"type": "errorMessage",
"types": {
"errorMessage": "One …
```

feat(ajv): Keep original validation type while using `errorMessage`

---

src/validateFieldsNatively.ts

Added a missing check to ensure `field` is defined, similar to the existing check in the preceding `if` condition.
Fixes #692 
@bluebill1049 Review is welcome, but please don’t merge. Thank you!

fix(validateFieldsNatively): handle undefined object when reading 'refs'

---

effect-ts/src/__tests__/__snapshots__/effect-ts.ts.snap
effect-ts/src/__tests__/effect-ts.ts
effect-ts/src/effect-ts.ts

feat(effectResolver): returns either all errors or only the first one based on `criteriaMode`

---

README.md

the provided link didn't go to related section of documentation

docs: update resolver documentation link

---

bun.lock
package.json
standard-schema/package.json
standard-schema/src/__tests__/__fixtures__/data.ts
standard-schema/src/__tests__/__snapshots__/standard-schema.ts.snap
standard-schema/src/__tests__/standard-schema.ts
standard-schema/src/standard-schema.ts

In StandardSchema issues, path segments can either be keys or an object with a `.key` value.
Current handling just calls `path.join('.')`, which would result in `"object Object"` if any path segments are objects.
The Standard Schema team have `@standard-schema/utils` which includes a `getDotPath` that handles segments correctly, so I've used that.

fix(standard-schema): Propertly handle object path segments 

---

src/__tests__/toNestErrors.ts
src/toNestErrors.ts

fix: escape square brackets in field name regex pattern

---

README.md
bun.lock
package.json
standard-schema/src/__tests__/__fixtures__/data.ts
standard-schema/src/__tests__/standard-schema.ts
typebox/src/__tests__/typebox.ts
typeschema/src/__tests__/Form-native-validation.tsx
typeschema/src/__tests__/Form.tsx
typeschema/src/__tests__/__fixtures__/data.ts
typeschema/src/__tests__/typeschema.ts
typeschema/src/typeschema.ts
zod/src/__tests__/Form-native-validation.tsx
zod/src/__tests__/Form.tsx
zod/src/__tests__/__fixtures__/data-v3.ts
zod/src/__tests__/__fixtures__/data-v4-mini.ts
zod/src/__tests__/__fixtures__/data-v4.ts
zod/src/__tests__/zod-v3.ts
zod/src/__tests__/zod-v4-mini.ts
zod/src/__tests__/zod-v4.ts
zod/src/zod.ts

Per some discussions I've been having with @bluebill1049, this PR adds support for Zod 4.
The other PR by @alexcraviotto (https://github.com/react-hook-form/resolvers/pull/776) is really solid but we decided to go another direction.
- This PR bumps the minimum Zod version to `3.25.0`
- With this change, it;s possible to support both Zod 3 and Zod 4 in a single `zodResolver` (via Zod's [subpath versioning](https://github.com/colinhacks/zod/issues/4371) scheme)
- I've designed this to continue working with Zod versions pre-3.25.0, but it's on a best-effort basis. For instance, you won't get perfect type signatures on parse params (the second argument to `zodResolver`). There were zero breaking changes between Zod 3.24 and Zod 3.25 so there's no reason not to upgrade.
Both Zod 3 and Zod 4 …

feat: support Zod 4

---

ajv/package.json
ajv/src/ajv.ts
bun.lock
package.json

related to https://github.com/react-hook-form/resolvers/issues/796

feat(ajv): add ajv-formats for ajvResolver

---

zod/src/zod.ts

This reverts commit bc09647a5eec21d07097a8ccf89fb52ebf50a1ec (PR #801).
---
I think #801 fix was not a typo.
When raw option is enabled, `TTransformedValues` should be `z.input`, not `z.output`.
```typescript
function zodResolver<
Input extends FieldValues,
Context,
Output,
T extends z4.$ZodType<Output, Input> = z4.$ZodType<Output, Input>,
>(
schema: z4.$ZodType<Output, Input>,
schemaOptions: Zod4ParseParams | undefined, // already partial
resolverOptions: RawResolverOptions,
): Resolver<z4.input<T>, Context, z4.output<T>>;
```
```typescript
export type Resolver<TFieldValues extends FieldValues = FieldValues, TContext = any, TTransformedValues = TFieldValues> = (values: TFieldValues, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => …
```

fix(zod): fix output type for Zod 4 resolver when raw option is enabled(#801)
